from funcionarios import *

funcionario1 = Funcionario("Gustavo Araújo de Menezes", "Auxiliar de Almoxarifado", 3500)
funcionario2 = Funcionario("Beatriz Cavalcanti", "Analista de RH", 4800)
funcionario3 = Funcionario("Marcos Vinícius Rocha", "Desenvolvedor Backend", 7500)
funcionario4 = Funcionario("Juliana Farias", "Gerente de Projetos", 9200)
funcionario5 = Funcionario("Ricardo Nunes", "Coordenador de Logística", 5600)
funcionario6 = Funcionario("Camila Oliveira", "Designer UI/UX", 6300)
funcionario7 = Funcionario("Fernando Souza", "Assistente Administrativo", 2800)
funcionario8 = Funcionario("Patrícia Almeida", "Especialista em Marketing", 7100)
funcionario9 = Funcionario("Larissa Mendes", "Auxiliar de Almoxarifado", 3450)
funcionario10 = Funcionario("Thiago Henrique Silva", "Analista de RH", 4900)
funcionario11 = Funcionario("Felipe Matos", "Desenvolvedor Backend", 7600)
funcionario12 = Funcionario("Ana Clara Peixoto", "Gerente de Projetos", 9500)
funcionario13 = Funcionario("Bruno Damasceno", "Coordenador de Logística", 5800)
funcionario14 = Funcionario("Letícia Guimarães", "Designer UI/UX", 6100)
funcionario15 = Funcionario("Roberto Carlos Lima", "Assistente Administrativo", 2750)
funcionario16 = Funcionario("Daniela Costa", "Especialista em Marketing", 7200)
funcionario17 = Funcionario("Eduardo Antunes", "Desenvolvedor Backend", 7400)
funcionario18 = Funcionario("Mariana Lopes", "Analista de RH", 4750)
funcionario19 = Funcionario("Sérgio Trindade", "Auxiliar de Almoxarifado", 3300)
funcionario20 = Funcionario("Renata Vasconcelos", "Assistente Administrativo", 2900)
